nameReference:
- kind: APIResourceSchema
  fieldSpecs:
  - kind: APIExport
    path: spec/latestResourceSchemas
- kind: ConfigMap
  fieldSpecs:
  - kind: Deployment
    path: spec/volumes/configMap/name

