apiVersion: tutorial.kubebuilder.io/v1alpha1
kind: Widget
metadata:
  labels:
    app.kubernetes.io/name: widget
    app.kubernetes.io/instance: widget-sample
    app.kubernetes.io/part-of: test-sdk
    app.kuberentes.io/managed-by: kustomize
    app.kubernetes.io/created-by: test-sdk
  name: widget-sample
spec:
  # TODO(user): Add fields here
